export const Actions = {
    SET_DATA:"SET_DATA",
    DELETE_USER:"DELETE_USER",
    SELECT_ITEM:"SELECT_ITEM",
    LEAVE_ITEM:"LEAVE_ITEM",
    INCREASE_COUNTER:"INCREASE_COUNTER",
    DECREASE_COUNTER:"DECREASE_COUNTER",
}