export const Actions = {
    SET_LOCATION:"SET_LOCATION",
    SELECT_ITEM:"SELECT_ITEM",
    SET_SELECTED_ITEMS:"SET_SELECTED_ITEMS",
    ADD_SELECTED_ITEMS:"ADD_SELECTED_ITEMS",
    SET_DIRECTORY_ITEMS:"SET_DIRECTORY_ITEMS",
    LEAVE_ITEM:"LEAVE_ITEM",
    CLEAR_SELECTED_ITEMS:"CLEAR_SELECTED_ITEMS",
    REMOVE_SELECTED_ITEM:"REMOVE_SELECTED_ITEM"
}