export const Messages = {
    SESSION_NOT_STARTED:"SESSION_NOT_STARTED",
    LOGIN_SUCCESSFULL:"LOGIN_SUCCESSFULL",
    DIRECTORY_CREATE_SUCCESS:"DIRECTORY_CREATE_SUCCESS",
    DIRECTORY_ALREADY_EXISTS:"DIRECTORY_ALREADY_EXISTS",
    ITEM_REMOVE_SUCCESS:"ITEM_REMOVE_SUCCESS",
    ITEM_RENAME_SUCCESS:"ITEM_RENAME_SUCCESS"
}