export const Actions = {
    SET_LOCATION:"SET_LOCATION",
    SET_START_LOCATION:"SET_START_LOCATION",
    ADD_DIRECTORY_ITEM:"ADD_DIRECTORY_ITEM",
    ADD_SELECTED_ITEM:"ADD_SELECTED_ITEM",
    SET_DIRECTORY_ITEMS:"SET_DIRECTORY_ITEMS",
    CLEAR_SELECTED_ITEMS:"CLEAR_SELECTED_ITEMS",
    REMOVE_SELECTED_ITEM:"REMOVE_SELECTED_ITEM",
    SET_SHOW_HIDDEN_FILES:"SET_SHOW_HIDDEN_FILES",
    SET_LOADING:"SET_LOADING",
    SET_ERROR:"SET_ERROR",
    RENAME_ITEM:"RENAME_ITEM"
}