export const Actions = {
    SET_LOCATION:"SET_LOCATION",
    SET_MODAL_LOADING:"SET_MODAL_LOADING",
    SET_START_LOCATION:"SET_START_LOCATION",
    SET_MODAL_LOCATION:"SET_MODAL_LOCATION",
    ADD_DIRECTORY_ITEM:"ADD_DIRECTORY_ITEM",
    ADD_SELECTED_ITEM:"ADD_SELECTED_ITEM",
    SET_DIRECTORY_ITEMS:"SET_DIRECTORY_ITEMS",
    SET_MODAL_DIRECTORY_ITEMS:"SET_MODAL_DIRECTORY_ITEMS",
    CLEAR_SELECTED_ITEMS:"CLEAR_SELECTED_ITEMS",
    REMOVE_SELECTED_ITEM:"REMOVE_SELECTED_ITEM",
    SET_LOADING:"SET_LOADING",
    SET_ERROR:"SET_ERROR",
    RENAME_ITEM:"RENAME_ITEM",
    ADD_SHARED_WITH:"ADD_SHARED_WITH",
    UPDATE_SHARED_WITH:"UPDATE_SHARED_WITH",
    DELETE_SHARED_WITH:"DELETE_SHARED_WITH"
}