export const Actions = {
    SET_LOCATION:"SET_LOCATION",
    SET_MODAL_LOADING:"SET_MODAL_LOADING",
    SET_START_LOCATION:"SET_START_LOCATION",
    SET_MODAL_LOCATION:"SET_MODAL_LOCATION",
    ADD_DIRECTORY_ITEM:"ADD_DIRECTORY_ITEM",
    ADD_SELECTED_ITEM:"ADD_SELECTED_ITEM",
    SET_DIRECTORY_ITEMS:"SET_DIRECTORY_ITEMS",
    SET_MODAL_DIRECTORY_ITEMS:"SET_MODAL_DIRECTORY_ITEMS",
    CLEAR_SELECTED_ITEMS:"CLEAR_SELECTED_ITEMS",
    REMOVE_SELECTED_ITEM:"REMOVE_SELECTED_ITEM",
    SET_LOADING:"SET_LOADING",
    SET_ERROR:"SET_ERROR",
    RENAME_ITEM:"RENAME_ITEM",
    ADD_SHARED_WITH:"ADD_SHARED_WITH",
    UPDATE_SHARED_WITH:"UPDATE_SHARED_WITH",
    DELETE_SHARED_WITH:"DELETE_SHARED_WITH",
    CLEAR_SELECTED_SHARED_WITH:"CLEAR_SELECTED_SHARED_WITH",

    ADD_UPLOAD_FILE:"ADD_UPLOAD_FILE",
    SET_UPLOAD_PROGRESS:"SET_UPLOAD_PROGRESS",
    SUCCESS_UPLOAD_FILE:"SUCCESS_UPLOAD_FILE",
    FAILURE_UPLOAD_FILE:"FAILURE_UPLOAD_FILE",

    ADD_DOWNLOAD_FILE:"ADD_DOWNLOAD_FILE",
    SET_DOWNLOAD_PROGRESS:"SET_DOWNLOAD_PROGRESS",
    SUCCESS_DOWNLOAD_FILE:"SUCCESS_DOWNLOAD_FILE",
    FAILURE_DOWNLOAD_FILE:"FAILURE_DOWNLOAD_FILE",

    SHOW_FILE_PROGRESS:"SHOW_FILE_PROGRESS",
    CLEAR_FILE_PROGRESS:"CLEAR_FILE_PROGRESS",

    SET_RECYCLE_BIN:"SET_RECYCLE_BIN",

    SET_PREVIEW_ACTIVE:"SET_PREVIEW_ACTIVE",
    SET_PREVIEW_DATA:"SET_PREVIEW_DATA",

    SET_RFM_CONFIG:"SET_RFM_CONFIG",
    SET_RFM_WINDOW:"SET_RFM_WINDOW",

    INCREASE_DEPTH:"INCREASE_DEPTH",
    INCREASE_MODAL_DEPTH:"INCREASE_MODAL_DEPTH",
    SET_DEPTH:"SET_DEPTH",
    SET_MODAL_DEPTH:"SET_MODAL_DEPTH",
    SET_CURRENT_DIR_CAN_WRITE:"SET_CURRENT_DIR_CAN_WRITE",
}